name: WakaTime Stats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update WakaTime API Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIME: "True"
